### ISSUE TITLE
Product Management >> Website >>Sorry, page was not loaded correctly 

### ISSUE THREAD

**Issue by sunilit42** [orocommerce/orocommerce#1]
Hello,

I am trying to install oscommerce in local system.

But category, pages not showing on frontend side.

Also when i go Product >> Websites >> click on any Store URL when getting below Error:
Sorry, page was not loaded correctly

**Comment by mbessolov** [comment]
The frontend part of the application is under development at this time.

**Comment by sunilit42** [comment]
Front End part mens showing category and pages on frontend?

And what about  Product >> Websites >> click on any Store URL when getting below Error:
Sorry, page was not loaded correctly

**Comment by mbessolov** [comment]
Yes, showing categories and products on the frontend is under development.

As for the websites - view/edit pages are not implemented yet.
