### ISSUE TITLE
Acessing /admin/config/system/commerce/pricing fails when default price list is deleted

### ISSUE THREAD

**Issue by DerJacques** [orocommerce/orocommerce#11]
Dear Orocommerce team,

We have been testing Orocmmerce for a couple of days now.
As part of the testing process, we deleted the default price list (which had the ID 1).
Since then, we have created two new lists, with one of them being the new default list.

However, when we now try to access the url `/admin/config/system/commerce/pricing`, Orocommerce fails with an error.
Looking at the logs, the following Exception is thrown:

`request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Price list record with id 1 not found, while reading default price list system configuration." at /var/www/orocommerce-application/vendor/oro/commerce/src/OroB2B/Bundle/PricingBundle/SystemConfig/PriceListConfigConverter.php line 111 {"exception":"[object] (InvalidArgumentException: Price list record with id 1 not found, while reading default price list system configuration. at /var/www/orocommerce-application/vendor/oro/commerce/src/OroB2B/Bundle/PricingBundle/SystemConfig/PriceListConfigConverter.php:111)"} []`

Do you know, why Orocommerce tries to find the not existing list with ID 1?

Best Regards,
Manuel

**Comment by DerJacques** [comment]
I asked the same question in the forums, and got a great reply:

https://www.orocommerce.com/forums/topic/accessing-adminconfigsystemcommercepricing-fails#post-1810

It does seem to be a bug, but there is a work-around until it has been resolved.

Here's the proposed work-around:
1. delete the price list configuration in the database:
`DELETE FROM oro_config_value WHERE name = 'default_price_lists';`

2. clear cache:
`rm -rf app/cache/dev app/cache/prod`

3. (optional) set another price list as default in the system configuration – go to System -> Configuration -> COMMERCE -> Catalog -> Pricing -> Default Price Lists

**Comment by manowark** [comment]
Hi, @DerJacques.

Is this issue still actual?

**Comment by DerJacques** [comment]
Hi @manowark

We are not using orocommerce at the moment, so unfortunately I am unable to answer your question.

**Comment by manowark** [comment]
@DerJacques, so can I close that issue?

**Comment by DerJacques** [comment]
Well, I would assume that this is still an issue if it hasn't been fixed, but it doesn't bother me anymore personally, so feel free to close it.
