### ISSUE TITLE
A broken symlink in backbone.paginator breaks the bundle autoloading

### ISSUE THREAD

**Issue by gplanchat** [orocommerce/orocommerce#12]
The link in `vendor/bower-asset/backbone.paginator/.npmignore` is broken on 1.0.0beta.5.

It makes break silently the loop processing of the `RecursiveDirectoryIterator` in `Oro\Bundle\DistributionBundle\OroKernel::findBundles`.

No error is returned, the file `app/cache/<env>/bundles.php` then contains an empty array.

To fix this, I had to delete the link manually

**Comment by mbessolov** [comment]
Please make sure you have the "fxp/composer-asset-plugin" [composer plugin installed globally](https://github.com/orocommerce/orocommerce-application/tree/1.0.0-beta.5#using-composer), and run `composer install` again.

**Comment by gplanchat** [comment]
Indeed, `fxp/composer-asset-plugin` is installed globally already but the issue appeared, still.

**Comment by mbessolov** [comment]
If the fxp/composer-asset-plugin is installed, then you should not have vendor/bower-asset/backbone.paginator directory at all. And if it is there for some reason - then it is not OroCommerce related as there is no such composer dependency  in OroCommerce application that would be installed in vendor folder.

**Comment by gplanchat** [comment]
It is a fresh install of the beta 5, fetched by `git clone` and `composer install`, no additional library was present

**Comment by gplanchat** [comment]
Isn't there a something to do to prevent this silent break ?

**Comment by aivus** [comment]
@gplanchat I have tested it. All works fine:
```
# composer global require "fxp/composer-asset-plugin:~1.2
# g clone git@github.com:orocommerce/orocommerce-application.git commerce_public
# cd commerce_public
# gco release/commerce-1.0.0-beta.5
# composer install
# app/console oro:install ...
```

```
Oro Application has been successfully installed in dev mode.
To run application in prod mode, please run cache:clear command with --env prod parameter
```

**Comment by sergeyz** [comment]
Here is check that should not allow installing if `fxp/composer-asset-plugin` plugin is missing https://github.com/orocommerce/orocommerce-application/blob/release/commerce-1.0.0-beta.5/composer.json#L36

In the end of `composer install` you should have an exception that will ask you to install plugin

**Comment by gplanchat** [comment]
Yes @sergeyz, I saw the test appearing on the last commit yesterday, I had to update the `fxp/composer-asset-plugin`version.

The original issue comes from this `\RecursiveDirectoryIterator` iterator: 
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DistributionBundle/OroKernel.php#L96

```php
<?php
    /**
     * Finds all .../Resource/config/oro/bundles.yml in given root folders
     *
     * @param array $roots
     *
     * @return array
     */
    protected function findBundles($roots = array())
    {
        $paths = array();
        foreach ($roots as $root) {
            if (!is_dir($root)) {
                continue;
            }
            $root   = realpath($root);
            $dir    = new \RecursiveDirectoryIterator($root, \FilesystemIterator::FOLLOW_SYMLINKS);
            $filter = new \RecursiveCallbackFilterIterator(
                $dir,
                function (\SplFileInfo $current) use (&$paths) {
                    $fileName = strtolower($current->getFilename());
                    if ($fileName === '.'
                        || $fileName === '..'
                        || $fileName === 'tests'
                        || $current->isFile()
                    ) {
                        return false;
                    }
                    if (!is_dir($current->getPathname() . '/Resources')) {
                        return true;
                    } else {
                        $file = $current->getPathname() . '/Resources/config/oro/bundles.yml';
                        if (is_file($file)) {
                            $paths[] = $file;
                        }

                        return false;
                    }
                }
            );

            $iterator = new \RecursiveIteratorIterator($filter);
            $iterator->rewind();
        }

        return $paths;
    }
```

While I had a broken symlink in the vendor dir, the iterator ended the loop, without throwing any exception or displaying any error information.

Maybe it is because of the ` \FilesystemIterator::FOLLOW_SYMLINKS`, I didn't test further (once the link deleted, it worked again properly) 

For the record, I'm using PHP 7.0 :

```
$ php -v
PHP 7.0.13 (cli) (built: Nov 15 2016 23:48:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13, Copyright (c) 1999-2016, by Zend Technologies

$ php -m
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by sergeyz** [comment]
Just faced with this issue. bower-asset vendor appears in vendors but it should not. Going to investigate it right now

**Comment by sergeyz** [comment]
I was not able to reproduce this case on a clean 1.0.0-beta.5 instance. Please remove vendors, revert composer.lock if you did `composer update` and do `composer install`

It looks like `vendor/bower-asset` appears after `composer update` with non-empty vendors folder and I'm going to investigate it too

**Comment by sergeyz** [comment]
Caused by missing

```
  "extra": {
    "asset-installer-paths": {
      "npm-asset-library": "web/bundles/npmassets",
      "bower-asset-library": "web/bundles/bowerassets"
    }
  }
```

make sure you use the proper application tag `git checkout tags/1.0.0-beta.5`

OroKernel.php will be fixed in any case

**Comment by gplanchat** [comment]
I was using branch `release/commerce-1.0.0beta.5`, not the tag (from https://github.com/orocommerce/orocommerce-application). Nevertheless the `extra` section contained the info you posted in your last message.

**Comment by sergeyz** [comment]
@gplanchat fixed by https://github.com/orocrm/platform/commit/66b9a371b22d9b35559d88a9a1623acd3c7a87eb#diff-86b34a281537a8a59f33555c7ffd0591R103
