### ISSUE TITLE
Typo in RequestProductItem association

### ISSUE THREAD

**Issue by krzysztofaraputa** [orocommerce/orocommerce#14]
Hi!
I found a typo in RequestProductItem entity. In $requestProduct field should be: `@ORM\ManyToOne(targetEntity="RequestProduct", inversedBy="requestProductItems")`
instead of 
`@ORM\ManyToOne(targetEntity="requestProduct", inversedBy="requestProductItems")`

This little thing causes huge problems with api processing (e.g. processor CompleteDefinition throws 'Class Oro\Bundle\RFPBundle\Entity\requestProduct does not exist').

**Comment by mbessolov** [comment]
@krzysztofaraputa  thank you for the bug report, it will be fixed shortly.

**Comment by mbessolov** [comment]
Fixed in 1.0.0 branch and will be available once released.
