### ISSUE TITLE
First Run: app/bootstrap.php.cache): failed to open stream:

### ISSUE THREAD

**Issue by astorm** [orocommerce/orocommerce#15]
Steps to Reproduce

1. Run `git clone --recursive -b 1.0.0 https://github.com/orocommerce/orocommerce-application.git`

2. Setup and Apache Virtualhost pointing to `web/` as the Docroot

3. Load URL in browser

Expected Behavior: Application runs or displays installation steps

Actual Behavior: Receive vague PHP error about cache file not being found

<img width="1434" alt="screen shot 2017-01-25 at 10 20 46 am" src="https://cloud.githubusercontent.com/assets/184372/22303416/11f86cb2-e2e8-11e6-99d8-89b0d81db1e0.png">

**Comment by aivus** [comment]
Hello, @astorm.

Please, follow this instruction: https://github.com/orocommerce/orocommerce-application#installation-instructions

**Comment by astorm** [comment]
@aivus Why aren't these instructions more prominent here? https://www.orocommerce.com/download

**Comment by astorm** [comment]
@aivus Also, thank you for the pointer!

**Comment by mbessolov** [comment]
Good catch!

The download page has been updated to encourage developers to check README.md for the installation instructions.

Thank you,
Michael
