### ISSUE TITLE
First Run on Command Line: app/bootstrap.php.cache): failed to open stream:

### ISSUE THREAD

**Issue by astorm** [orocommerce/orocommerce#16]
Steps to Reproduce

1. Run git clone --recursive -b 1.0.0 https://github.com/orocommerce/orocommerce-application.git

2. Attempt to run Symfony console with `php app/console`

Expected Behavior: See list of Commands

Actual Behavior: See vague warning about missing cache file. 

    $ php app/console
    PHP Warning:  require_once(/path/to/oro/orocommerce-application/app/bootstrap.php.cache): failed to open stream: No such file or directory in /path/to/oro/orocommerce-application/app/console on line 10
    PHP Stack trace:
    PHP   1. {main}() /path/to/oro/orocommerce-application/app/console:0

    Warning: require_once(/path/to/oro/orocommerce-application/app/bootstrap.php.cache): failed to open stream: No such file or directory in /path/to/oro/orocommerce-application/app/console on line 10

    Call Stack:
        0.0002     358608   1. {main}() /path/to/oro/orocommerce-application/app/console:0

    PHP Fatal error:  require_once(): Failed opening required '/path/to/oro/orocommerce-application/app/bootstrap.php.cache' (include_path='.:/usr/local/php5/lib/php') in /path/to/oro/orocommerce-application/app/console on line 10
    PHP Stack trace:
    PHP   1. {main}() /path/to/oro/orocommerce-application/app/console:0

    Fatal error: require_once(): Failed opening required '/path/to/oro/orocommerce-application/app/bootstrap.php.cache' (include_path='.:/usr/local/php5/lib/php') in /path/to/oro/orocommerce-application/app/console on line 10

    Call Stack:
        0.0002     358608   1. {main}() /path/to/oro/orocommerce-application/app/console:0

**Comment by mbessolov** [comment]
Hi Alan,

Please make sure to install the application before trying to run any Symfony commands, as it requires the application to be installed.

The installation process is described in the application's README.md file - see https://github.com/orocommerce/orocommerce-application#installation-instructions

Thank you,
Michael

**Comment by astorm** [comment]
@mbessolov Thanks for the quick response -- any reason these instalation instructions aren't listed here? https://www.orocommerce.com/download  The implication of that download page is you can github and go.  A little more context there might help developers who are interested in checking out Oro but less persistent :)

**Comment by mbessolov** [comment]
Good catch!

The download page has been updated to encourage developers to check README.md for the installation instructions.

Thank you,
Michael
