### ISSUE TITLE
Installation Error: The process has been signaled with signal "11".         

### ISSUE THREAD

**Issue by astorm** [orocommerce/orocommerce#17]
When running the installer with

    $ php app/console oro:install --env=prod --timeout=0 -vvv

the installation process errors out with *The process has been signaled with signal "11"*.  Full `-vvv` stack trace below.

    Load sample data (y/n): y
    Loading "demo" data fixtures ...
      > loading Oro\Bundle\LocaleBundle\Migrations\Data\Demo\ORM\LoadLocalizationDemoData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadLeadSourceData
      > loading Oro\Bundle\RFPBundle\Migrations\Data\Demo\ORM\LoadRequestStatusDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadPriceAttributePriceListDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadPriceListDemoData
      > loading Oro\Bundle\PaymentTermBundle\Migrations\Data\Demo\ORM\LoadPaymentTermDemoData
      > loading Oro\Bundle\PaymentTermBundle\Migrations\Data\Demo\ORM\LoadPaymentRuleDemoData
      > loading Oro\Bundle\CMSBundle\Migrations\Data\Demo\ORM\LoadPageDemoData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadCustomerGroupDemoData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadCustomerInternalRatingDemoData
      > loading Oro\Bundle\ProductBundle\Migrations\Data\Demo\ORM\LoadProductDemoData
      > loading Oro\Bundle\CatalogBundle\Migrations\Data\Demo\ORM\LoadCategoryDemoData
      > loading Oro\Bundle\ShippingBundle\Migrations\Data\Demo\ORM\LoadShippingOriginConfigurationDemoData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadBusinessUnitData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadGroupData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadChannelData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadEmbeddedFormData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadReportData
      > loading Oro\Bundle\WebCatalogBundle\Migrations\Data\Demo\ORM\LoadWebCatalogDemoData
      > loading Oro\Bundle\ProductBundle\Migrations\Data\Demo\ORM\LoadProductUnitPrecisionDemoData
      > loading Oro\Bundle\CatalogBundle\Migrations\Data\Demo\ORM\LoadProductCategoryDemoData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadCustomerDemoData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadScopeCustomerDemoData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadScopeCustomerGroupDemoData
      > loading Oro\Bundle\VisibilityBundle\Migrations\Data\Demo\ORM\LoadCategoryVisibilityDemoData
      > loading Oro\Bundle\VisibilityBundle\Migrations\Data\Demo\ORM\LoadProductVisibilityDemoData
      > loading Oro\Bundle\PaymentTermBundle\Migrations\Data\Demo\ORM\LoadPaymentTermToAccountDemoData
      > loading Oro\Bundle\PaymentTermBundle\Migrations\Data\Demo\ORM\LoadPaymentTermToAccountGroupDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadPriceListToCustomerGroupDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadPriceListToWebsiteDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadProductPriceDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadPriceAttributeProductPriceDemoData
      > loading Oro\Bundle\TaxBundle\Migrations\Data\Demo\ORM\LoadTaxTableRatesDemoData
      > loading Oro\Bundle\AlternativeCheckoutBundle\Migrations\Data\Demo\ORM\UpdateAlternativeCheckoutWorkflowStatus
      > loading Oro\Bundle\InventoryBundle\Migrations\Data\Demo\ORM\LoadFallbackFieldsData
      > loading Oro\Bundle\InventoryBundle\Migrations\Data\Demo\ORM\LoadInventoryLevelDemoData
      > loading Oro\Bundle\SEOBundle\Migrations\Data\Demo\ORM\LoadCategoryDemoMetaData
      > loading Oro\Bundle\SEOBundle\Migrations\Data\Demo\ORM\LoadPageDemoMetaData
      > loading Oro\Bundle\SEOBundle\Migrations\Data\Demo\ORM\LoadProductDemoMetaData
      > loading Oro\Bundle\ShippingBundle\Migrations\Data\Demo\ORM\LoadProductShippingOptionsDemoData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadUserData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadContactGroupData
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadEmailTemplates
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadPintabsData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadCustomerUserDemoData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadCustomerUserAddressDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadPriceListToCustomerDemoData
      > loading Oro\Bundle\RFPBundle\Migrations\Data\Demo\ORM\LoadRequestDemoData
      > loading Oro\Bundle\InvoiceBundle\Migrations\Data\Demo\ORM\LoadInvoiceDemoData
      > loading Oro\Bundle\InvoiceBundle\Migrations\Data\Demo\ORM\LoadInvoiceLineItemDemoData
      > loading Oro\Bundle\ShoppingListBundle\Migrations\Data\Demo\ORM\LoadShoppingListDemoData
      > loading Oro\Bundle\TaxBundle\Migrations\Data\Demo\ORM\LoadTaxConfigurationDemoData
      > loading Oro\Bundle\SaleBundle\Migrations\Data\Demo\ORM\LoadQuoteDemoData
      > loading Oro\Bundle\ShoppingListBundle\Migrations\Data\Demo\ORM\LoadLineItemDemoData
      > loading Oro\Bridge\TaskCRM\Migrations\Data\Demo\ORM\UpdateTaskAccessLevels
      > loading Oro\Bundle\DemoDataBundle\Migrations\Data\Demo\ORM\LoadUsersData
      > loading Oro\Bundle\CustomerBundle\Migrations\Data\Demo\ORM\LoadCustomerAddressDemoData
      > loading Oro\Bundle\PricingBundle\Migrations\Data\Demo\ORM\LoadCombinedPriceListDemoData
      > loading Oro\Bundle\OrderBundle\Migrations\Data\Demo\ORM\LoadOrderDemoData
      > loading Oro\Bundle\OrderBundle\Migrations\Data\Demo\ORM\LoadOrderLineItemDemoData

                                                          
      [Symfony\Component\Process\Exception\RuntimeException]  
      The process has been signaled with signal "11".         
                                                          

    Exception trace:
     () at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:371
     Symfony\Component\Process\Process->wait() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:203
     Symfony\Component\Process\Process->run() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:135
     Oro\Bundle\InstallerBundle\CommandExecutor->runCommand() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/InstallCommand.php:508
     Oro\Bundle\InstallerBundle\Command\InstallCommand->loadDataStep() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/InstallCommand.php:139
     Oro\Bundle\InstallerBundle\Command\InstallCommand->execute() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
     Symfony\Component\Console\Command\Command->run() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:866
     Symfony\Component\Console\Application->doRunCommand() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
     Symfony\Component\Console\Application->doRun() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
     Symfony\Component\Console\Application->run() at /Users/alanstorm/Sites/oro-commerce-1-0-0.dev/orocommerce-application/app/console:22

    oro:install [--application-url [APPLICATION-URL]] [--organization-name [ORGANIZATION-NAME]] [--user-name [USER-NAME]] [--user-email [USER-EMAIL]] [--user-firstname [USER-FIRSTNAME]] [--user-lastname [USER-LASTNAME]] [--user-password [USER-PASSWORD]] [--skip-assets] [--force] [--symlink] [--sample-data [SAMPLE-DATA]] [--drop-database] [--skip-translations] [--force-debug] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--disabled-listeners DISABLED-LISTENERS] [--] <command>

**Comment by mbessolov** [comment]
Let me guess - Mac OS and PHP 7.x binaries from liip.ch?
These binaries are prone to segfaults (that's what Symfony sees as "signal 11").
I recommend to install PHP 7.x from ports or brew - and the segfaults will go away.

**Comment by astorm** [comment]
You're correct @mbessolov and -- fair enough choosing not to support liip.  FWIW among a certain set of developers it's a pretty popular way to get a modern-ish PHP on OS X/MacOS, and a case could be made that Oro's process handling code should take these sorts of things into account if you're trying to push adoption (especially since it seems you're super familiar with the problem (-:)

Regardless -- at least it's documented for others now.  Closing out -- feel free to reopen if you want to address it, and let Motti know I gave things a spin :)

**Comment by sergeyz** [comment]
@astorm, please check https://github.com/symfony/symfony/issues/21349 and https://bugs.php.net/bug.php?id=73989 for more details. There is nothing we can do more

**Comment by astorm** [comment]
Thanks for following @sergeyz -- although I'd correct you slightly to say there's nothing more you chose to do, since fixing this would involve Oro working around the seg fault errors in the Symfony Bundle.

**Comment by sergeyz** [comment]
@astorm 

It's not even Symfony's bug, segfaults are PHP errors and the reason somewhere in PHP distribution. There is no clear steps to reproduce and no workaround from PHP script side. Quick bug overview tells me that issue somewhere in Reflection and GC, we had the issue once and reported it https://bugs.php.net/bug.php?id=73667.

So, the actual reason somewhere in the list https://bugs.php.net/search.php?cmd=display&search_for=Segfaults&order_by=ts1&direction=ASC&limit=30&status=Open&reorder_by=ts1. So what should we do here?
