### ISSUE TITLE
OroCommerce Application php 7.0 Vagrant Session Handling. 

### ISSUE THREAD

**Issue by duffner** [orocommerce/orocommerce#18]
I'm currently running a vagrant box on a Mac, and I'm getting an issue with sessions on installation. 

( ! ) Warning: SessionHandler::read(): Session data file is not created by your uid in /var/www/orodemo_orocommerce/html/app/cache/prod/classes.php on line 416

( ! ) Warning: SessionHandler::write(): Session data file is not created by your uid in /var/www/orodemo_orocommerce/html/app/cache/prod/classes.php on line 420

( ! ) Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/www/orodemo_orocommerce/html/app/cache/sessions) in /var/www/orodemo_orocommerce/html/app/cache/prod/classes.php on line 161

This issue appears to be related to php 7.0 and session path being not writable. Updating the session path save from the local file system to php's session location resolved the problem. 

As this appears to be a Symfony issue, I'm not sure if the Oro team has any plans or recommendations.   Has your team experienced this before on Vagrant and if so what is the best path towards resolution?

**Comment by zeykzso** [comment]
Hello @duffner and thank you for your question!

My first guess would be that the folder `app/cache/sessions` didn't have enough permissions for the session handler. 
Did you setup them correctly? You can follow this [documentation](http://symfony.com/doc/2.8/setup/file_permissions.html) from Symfony.
Also [this reply](http://stackoverflow.com/a/40950692) could help you.

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
