### ISSUE TITLE
Is there demo

### ISSUE THREAD

**Issue by fazliddin** [orocommerce/orocommerce#2]
Hi, I am web developer, I am very interested in your project.
Is there demo to see how it works.

**Comment by mbessolov** [comment]
You can download OroCommerce application and see how it works locally - please follow the installation instructions at https://github.com/orocommerce/orocommerce-application#installation-instructions.

A public demo website for non-developers will be set up later, once we have the alpha release out 'officially'.

**Comment by mbessolov** [comment]
(just to close the loop on this one for everyone who arrives via search)

The public OroCommerce demo is available at https://www.orocommerce.com/demo

OroCommerce Community Edition can be downloaded (both source archive, and a virtual machine image) at https://www.orocommerce.com/download
