### ISSUE TITLE
anyway to show more stack  info 

### ISSUE THREAD

**Issue by videni** [orocommerce/orocommerce#22]
I add a none existed function , it only shows  following stack info

``` 
 Fatal error: Uncaught Error: Call to undefined function Oro\Bundle\SecurityBundle\ORM\Walker\breakhere() in /private/var/www/orocommerce-application/vendor/oro/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/OwnershipConditionDataBuilder.php on line 224
( ! ) Error: Call to undefined function Oro\Bundle\SecurityBundle\ORM\Walker\breakhere() in /private/var/www/orocommerce-application/vendor/oro/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/OwnershipConditionDataBuilder.php on line 224
Call Stack
#	Time	Memory	Function	Location
1	0.0002	362736	{main}( )	.../app_dev.php:0
2	0.0011	485712	Symfony\Component\HttpKernel\Kernel->handle( )	.../app_dev.php:34
3	0.1373	7499480	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	.../Kernel.php:185

```

it seems oro-platform hides lots of stack information, anyway to show more ?

**Comment by dandries** [comment]
Hi Videni,

    Can you please tell me what stack info are you referring to? Is it from the profiler or from logs?
    Also, what information do you want to obtain, in order to see how I can help?

Thanks.

**Comment by videni** [comment]
@dandries , thanks for your help , a standard symfony stack info should be like this 

```
in DomainResolverListener.php line 45
at DomainResolverListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
at call_user_func(array(object(DomainResolverListener), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher)) in WrappedListener.php line 106
at WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
at call_user_func(object(WrappedListener), object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher)) in EventDispatcher.php line 174
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent)) in EventDispatcher.php line 43
at EventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in TraceableEventDispatcher.php line 136
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in HttpKernel.php line 129 
at HttpKernel->handleRaw(object(Request), 1) in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, true) in Kernel.php line 168
at Kernel->handle(object(Request)) in app_dev.php line 28
```

but oro-platform somehow hides them.

**Comment by dandries** [comment]
Hi,
    It is a possibility that  you have some specific settings on your environment which may be causing this.
    For example, what is your setting on the nesting level for the xdebug? In the system requirements it is recommended to have a higher value for this [https://www.orocrm.com/documentation/2.0/system-requirements#optional-recommendations](https://www.orocrm.com/documentation/2.0/system-requirements#optional-recommendations) (my local setting for example is 1000).
 
    A check on the platform shows that the platform itself does not hide information or chunks the stack trace.

`PHP Fatal error:  Call to undefined function Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\unknownFunction() in /opt/www/mono/package/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/OwnershipConditionDataBuilder.php on line 224, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP Stack trace:, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   1. {main}() /opt/www/mono/application/commerce-enterprise/web/app_dev.php:0, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle() /opt/www/mono/application/commerce-enterprise/web/app_dev.php:30, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   3. Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle() /opt/www/mono/application/commerce-enterprise/app/bootstrap.php.cache:2540, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /opt/www/mono/application/commerce-enterprise/app/bootstrap.php.cache:3355, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /opt/www/mono/application/commerce-enterprise/app/bootstrap.php.cache:3201, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   6. call_user_func_array:{/opt/www/mono/application/commerce-enterprise/app/bootstrap.php.cache:3242}() /opt/www/mono/application/commerce-enterprise/app/bootstrap.php.cache:3242, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   7. Oro\\Bundle\\DashboardBundle\\Controller\\DashboardController->viewAction() /opt/www/mono/application/commerce-enterprise/app/bootstrap.php.cache:3242, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   8. Oro\\Bundle\\DashboardBundle\\Model\\Manager->findAllowedDashboards() /opt/www/mono/package/platform/src/Oro/Bundle/DashboardBundle/Controller/DashboardController.php:95, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP   9. Oro\\Bundle\\SecurityProBundle\\ORM\\Walker\\AclHelper->apply() /opt/www/mono/package/platform/src/Oro/Bundle/DashboardBundle/Model/Manager.php:271, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  10. Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\AclHelper->apply() /opt/www/mono/package/platform-enterprise/src/Oro/Bundle/SecurityProBundle/ORM/Walker/AclHelper.php:39, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  11. Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\AclHelper->processSelect() /opt/www/mono/package/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/AclHelper.php:134, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  12. Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\AclHelper->processRangeVariableDeclaration() /opt/www/mono/package/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/AclHelper.php:258, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  13. Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\OwnershipConditionDataBuilder->getAclConditionData() /opt/www/mono/package/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/AclHelper.php:396, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  14. Oro\\Bundle\\SecurityProBundle\\ORM\\Walker\\OwnershipProConditionDataBuilder->buildConstraintIfAccessIsGranted() /opt/www/mono/package/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/OwnershipConditionDataBuilder.php:132, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  15. Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\OwnershipConditionDataBuilder->buildConstraintIfAccessIsGranted() /opt/www/mono/package/platform-enterprise/src/Oro/Bundle/SecurityProBundle/ORM/Walker/OwnershipProConditionDataBuilder.php:70, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  16. Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\OwnershipConditionDataBuilder->getCondition() /opt/www/mono/package/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/OwnershipConditionDataBuilder.php:209, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  17. Oro\\Bundle\\SecurityProBundle\\ORM\\Walker\\OwnershipProConditionDataBuilder->getOrganizationId() /opt/www/mono/package/platform/src/Oro/Bundle/SecurityBundle/ORM/Walker/OwnershipConditionDataBuilder.php:366, referer: http://b2b.ee.mono.dev/app_dev.php/admin/user/login
 PHP  18. Oro\\Bundle\\SecurityBundle\\ORM\\Walker\\OwnershipConditionDataBuilder->getOrganizationId() /opt/www/mono/package/platform-enterprise/src/Oro/Bundle/SecurityProBundle/ORM/Walker/OwnershipProConditionDataBuilder.php:98, referer: http://b2b.ee.mono.dev`

**Comment by videni** [comment]
@dandries , I disabled xdebug, it is still the same , but the same environment works for symfony 3.2, here is my php version info
```
PHP 7.0.14 (cli) (built: Dec  9 2016 07:34:25) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14, Copyright (c) 1999-2016, by Zend Technologies
    with blackfire v1.14.1~mac-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.
```

**Comment by dandries** [comment]
So on the same env, on a symfony app it shows full stack for an exception and on an orocommerce app it behaves like you specified in first post? (using the same approach, by adding usage of an undefined function)
    Your objective is to see the full method call stack to the point where you've inserted the undefined function?
    Do you have any specific php error_reporting settings made on your env?

**Comment by videni** [comment]
@dandries ,  I don't change anything in a fresh cloned oro-commerce repo, I also cloned oro-crm ,they both  don't show the full method call stack .

**Comment by AlexPuscas** [comment]
Hello @videni,

What I think you are trying to point out is that you face a PHP Error instead of an Exception that can be handled by Symfony.
This issue appears because ORO registers an own ErrorHandler, instead of the one from Symfony. Links to both ErrorHandlers below:
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DistributionBundle/Error/ErrorHandler.php
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/ErrorHandler.php

We are aware of the issue you are facing, it will be solved soon.

Since this is a `dev environment` tool, what you can do on your `local application`, already installed, in order to take advantage of the ErrorHandler from Symfony is not to register the ErrorHandler from ORO. Simply comment/delete this line: https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DistributionBundle/Error/ErrorHandler.php#L32

Hope this helps you out!

**Comment by videni** [comment]
@AlexPuscas ,  thanks for you help , I comment that line as you said , but  it doesn't work

```
( ! ) Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "breakhere" from namespace "Oro\Bundle\SecurityBundle\Annotation". in /private/var/www/orocommerce-application/vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Annotation/Acl.php on line 66
( ! ) Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "breakhere" from namespace "Oro\Bundle\SecurityBundle\Annotation". in /private/var/www/orocommerce-application/vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Annotation/Acl.php on line 66
Call Stack
#	Time	Memory	Function	Location
1	0.5897	71209792	Symfony\Component\Debug\ErrorHandler->handleException( )	.../ErrorHandler.php:0
2	3.8928	79344288	Symfony\Component\Debug\ErrorHandler->handleException( )	.../ErrorHandler.php:597

```

**Comment by zeykzso** [comment]
Hi @videni 

Can you please modify your application's `web/app_dev.php` file, calling `Debug::enable()`?

```php
(...)
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Debug\Debug;
(...)

Debug::enable();
$kernel = new AppKernel('dev', true);
```
Is this making a difference?
Thank you

**Comment by videni** [comment]
@zeykzso ,  thanks for your help,  it is default code in app_dev.php, so it won't make difference .
@AlexPuscas , I update the code  and try your way , it works now.  thanks  a lot.
