### ISSUE TITLE
OroCommerce - BO is broken

### ISSUE THREAD

**Issue by XaBe20** [orocommerce/orocommerce#23]
When I change the value of "css_debug_all" in config_dev.yml (false to true), the back-office is broken

## app/config/config_dev.yml
```
oro_assetic:
    css_debug:      ~
    css_debug_all:  true

```

After this changement, I execute cache/assets/assetic

```
app/console cache:clear
app/console oro:assets:install
app/console assetic:dump

```

It's normal ?

**Comment by AlexPuscas** [comment]
Hello @XaBe20,

I see you are trying to debug theme styles. Please take a look at ThemeBundle documentation:
https://github.com/orocrm/platform/tree/master/src/Oro/Bundle/ThemeBundle#debugging-theme-styles

As you can see there, you shouldn't run `assetic:dump` in case you set `css_debug_all` to `true`. Here is the documentation section:
> app/console assetic:dump # if you are not using oro_assetic.css_debug: [theme] or oro_assetic.css_debug_all: true options

If you need more clarifications, please let me know.
Alex

**Comment by XaBe20** [comment]
Thank you @AlexPuscas 
The problem comes from me.
I activated _css_debug_all_ and I launched _assetic:dump_
Thanks for the quick reply

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
