### ISSUE TITLE
RedirectBundle\Generator\SlugEntityGenerator::generate() null given

### ISSUE THREAD

**Issue by blump** [orocommerce/orocommerce#25]
Hello,
Here's the error when I run
`app/console oro:message-queue:consume --env=prod`

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Oro\Bundle\RedirectBundle\Generator\SlugEntityGenerator::generate() must implement interface Oro\Bundle\RedirectBundle\Entity\SluggableInterface, null given, called in /www/oro/vendor/oro/commerce/src/Oro/Bundle/RedirectBundle/Async/DirectUrlProcessor.php on line 81 and defined in /www/oro/vendor/oro/commerce/src/Oro/Bundle/RedirectBundle/Generator/SlugEntityGenerator.php:33
Stack trace:
#0 /www/oro/vendor/oro/commerce/src/Oro/Bundle/RedirectBundle/Async/DirectUrlProcessor.php(81): Oro\Bundle\RedirectBundle\Generator\SlugEntityGenerator->generate(NULL)
#1 /www/oro/vendor/oro/platform/src/Oro/Component/MessageQueue/Client/DelegateMessageProcessor.php(36): Oro\Bundle\RedirectBundle\Async\DirectUrlProcessor->process(Object(Oro\Component\MessageQueue\Transport\Dbal\DbalMessage), Object(Oro\Component\MessageQueue\Transport\Dbal\DbalSession))
#2 /www/oro/vendor/oro/platform/src/Oro/Component/MessageQueue/Consumption/QueueConsumer.php(182): Oro\Component`

Here is my config (Oro CRM + Oro Commerce)

<img width="660" alt="capture d ecran 2017-02-28 a 17 33 47" src="https://cloud.githubusercontent.com/assets/10714122/23414662/05e77322-fddd-11e6-9249-0e9c36b5f125.png">

Do you have an idea ?

**Comment by blump** [comment]
After reinstalling with the sample data, it's ok ! Good job

**Comment by aivus** [comment]
Hello @blump 
Could you confirm that this exception thrown in case of install without sample data?

Thanks
