### ISSUE TITLE
RuntimeException with CLI install

### ISSUE THREAD

**Issue by ajardin** [orocommerce/orocommerce#28]
Hello,

I'm trying to make a fresh install locally but I'm facing a weird issue.

```
$ php app/console oro:install --env=prod --timeout=0
Installing Oro Application.

...

[RuntimeException]
  Failed migrations: Oro\Bundle\UserBundle\Migrations\Schema\OroUserBundleInstaller.

oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--disabled-listeners DISABLED-LISTENERS] [--] <command>
```

- [The full console output](https://github.com/orocommerce/orocommerce/files/893898/console.txt)
- [My PHP Configuration](https://github.com/orocommerce/orocommerce/files/893892/php.txt)

Is there any workaround for this issue?
I'll continue my investigations tomorrow but if somebody has an idea in the meantime... ;-)

**Comment by sergeyz** [comment]
Hi, @ajardin! Please disable opcache for CLI
`opcache.enable_cli => On => On` and try install again

**Comment by ajardin** [comment]
Hi @sergeyz, still the same issue with `opcache.enable_cli` disabled.

**Comment by sergeyz** [comment]
@ajardin please make sure your database and caches are empty before install

**Comment by ajardin** [comment]
You were right, the process almost finished this time!
But... I've received another error during the cache clearing. :-/

```
Launching "Update website URL" (/var/www/html/orocommerce/vendor/oro/commerce/src/Oro/Bundle/WebsiteBundle/install.php) script


 // Clearing the cache for the prod environment with debug false

Segmentation fault


  [RuntimeException]
  The command '/usr/local/bin/php' 'app/console' 'cache:clear' '--env=prod' terminated with an exit code: 139.

```

**Comment by romeof1980** [comment]
I have the same problem with oro commerce community edition 5.1.0 when launching `bin/console oro:install --drop-database`
env:
php 8.2 with postgres 15.1 (node v18.20.6, npm v9.3.1).

how to reproduce:
I tried to `rm -rf var/cache/*` and `oro:install --drop-database`
I also tried disabling opcache in my docker configuration and now  `php -i | grep 'opcache.enable'` gives an empty string stating opcache is disabled.

but the following error continues popping up:

```
In MigrationExecutor.php line 110:
                                                                               
  Failed migrations: Oro\Bundle\PlatformBundle\Migrations\Schema\OroPlatformB  
  undleInstaller.                                                              
                                                                               

oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [--timeout [TIMEOUT]]

The command '/usr/local/bin/php' 'bin/console' 'oro:migration:load' '--force' '--timeout=3600' '--env=prod' terminated with an exit code: 1.
```

**Comment by romeof1980** [comment]
This was weird because I had to delete manually the db from the postgres container. It seems the --drod-database option did not work as expected even if during `oro:install` I got the green output "Drop schema." without errors.
