### ISSUE TITLE
Front-end brakes when Products in the shopping-list are changed in the admin.

### ISSUE THREAD

**Issue by Dr-Head** [orocommerce/orocommerce#29]
**Duplication steps**
1. Add a configurable product to my shopping list.
2. Then uncheck(removed and added them back _not delete_) the children products and rechecked them in the admin.
3. Then go back to the front-end and we get an error about: 
"Can't 'getString()' of value Null"

```
Line 156 of mvp-swag/vendor/oro/commerce/src/Oro/Bundle/ShoppingListBundle/Entity/Repository/LineItemRepository.php 

$productName = $lineItem->getProduct()->getName()->getString();
```

_Temporary resolution_
The only way I could resolve this issue was to comment out the line and then the front-end would load. 
Then I had to go in and remove the item from my shopping-list.

**Comment by manowark** [comment]
Hi, @Dr-Head. Thank you.

I'll try to reproduce that on my environment today and let you know.

**Comment by manowark** [comment]
@Dr-Head, we tried to reproduce this issue and we couldn't. Could you please provide detailed steps to reproduce that issue and version of application?

**Comment by mozillalives** [comment]
@manowark @Dr-Head is out for a little bit. In his place I'll try to reproduce this issue next Monday to provide you with the necessary steps to reproduce.

**Comment by mozillalives** [comment]
I'm sorry for the delay in updating this but other projects stole my attention earlier this week. I tried to reproduce the issue locally as well but I wasn't able to. I think we'll have to wait until @Dr-Head returns to figure this out.

**Comment by Dr-Head** [comment]
[https://youtu.be/6AZW_ZTEA7Q](url)

PHP -v: 5.6.30
oro/commerce-enterprise: 1.0.2

Also I'll note that this brakes all pages not just the product page, returning the same error.

**Comment by aivus** [comment]
Hi, @Dr-Head.

Sorry for such a long delay.
I just checked case from the video on commerce 1.2 and it works without any errors.

Please confirm that it works for you too.

Thanks.

**Comment by mozillalives** [comment]
Hi @aivus, I'll take over for @Dr-Head. We're still running a previous version. Let me update to 1.2 and I'll check to see if that fixes the issue for us.

**Comment by manowark** [comment]
Hi, @mozillalives. Recently we released 1.3 version. Did you update to it and that issue still actual?

**Comment by mozillalives** [comment]
Hi @manowark. I haven't had a chance to test it yet but I'll let you know as soon as I do.

**Comment by mozillalives** [comment]
@manowark I'm sorry, I haven't had the time to circle back on this. How about we just close it and if I see it again, I'll file a new ticket. Sound good?

**Comment by aivus** [comment]
@mozillalives thanks. I'm closing this issue. Feel free to reopen if you get it again.
