### ISSUE TITLE
Install: Requirements validation for PHP CLI

### ISSUE THREAD

**Issue by jorgevrgs** [orocommerce/orocommerce#31]
X-Powered-By: PHP/7.0.18
Content-type: text/html; charset=UTF-8

Requirements validation for PHP CLI

CHECK:
If you have multiple PHP versions installed, you need to configure ORO_PHP_PATH variable with PHP binary path used by web server

* Missing specific solution.

**Comment by mkudelya** [comment]
Hi @jorgevrgs 

Try to set our ORO_PHP_PATH environment variable via  `export ORO_PHP_PATH=[path to php]` command or update your .bash_profile. Please take a look on [acticle](https://www.cyberciti.biz/faq/set-environment-variable-linux/).

**Comment by manowark** [comment]
@jorgevrgs, please tell is this issue still actual for you?

**Comment by jorgevrgs** [comment]
Yes. It's not possible to install in a shared hosting. Then VPS is required to be able to make this change.

**Comment by manowark** [comment]
Hm, do you have ssh access to your instance and do you can edit .bash_profile?

**Comment by JetJsF** [comment]
@jorgevrgs beware "shared hosting" because as usual they have limit on count of open files(for example 2000 and it can't be increased). Such amount(and even more) of files can be easily required during cache warm up

**Comment by manowark** [comment]
@jorgevrgs, could you provide more info to have possibility to help you? Or I can close this issue?

**Comment by jorgevrgs** [comment]
It's important to make that clarification, "install only with root permissions" because in a shared hosting is impossible. Or, if you can improve installation requirements your service will be better.

**Comment by mbessolov** [comment]
You do not need root permissions to install the application. Actually it is not recommended to install it as root.

You just need a system that you can fully control via control panel, root access or by posting a ticket to the hosting provider.
