### ISSUE TITLE
Disabled product is accesible by frontend

### ISSUE THREAD

**Issue by tjurczak** [orocommerce/orocommerce#34]
If product is disabled there is possibility to show it on frontend. Just replace ID in URL (http://localhost:3080/app_dev.php/product/view/67).

**Comment by d-beekeeper** [comment]
Thanks for notice, tjurczak.
We will fix it in nearest releases.

**Comment by oroavinogradov** [comment]
This issue is fixed since OroCommerce v1.4

**Comment by tjurczak** [comment]
I think that this issue should be also fix in 1.3.* because of LTS. Is it possible?

**Comment by mbessolov** [comment]
@tjurczak you can find and apply necessary changes in 3c3d8599873a989d68857821b1a53f0fcb8d124c
Patch releases for older version are provided only to the Enterprise Edition customers.
