### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by davea571** [orocommerce/orocommerce#35]
Mac OS 10.12.6
php 7.1.5 from homebrew
running installer with 

php app/console oro:install  --env=prod --timeout=0

I'm getting an error at 
16:24:16 [file+] /Library/WebServer/Documents/orocommerce-application/web/js/oro.min.js
Launching "Update website URL" (/Library/WebServer/Documents/orocommerce-application/vendor/oro/commerce/src/Oro/Bundle/WebsiteBundle/install.php) script

 // Clearing the cache for the prod environment with debug false                                                        

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "11". 

I previously had a similar error earlier in the install process when I was using the php from liip.ch, but I saw the post in another thread saying that was a problematic package.  Going to homebrew for apache and php got me much farther along, but still not all the way there.

**Comment by mkudelya** [comment]
Hi @davea571 

Probably it is a php bug. Please look at [this topic](https://github.com/symfony/symfony/issues/20988).

**Comment by mkudelya** [comment]
Could you please test your installation on version 7.0.* ?

**Comment by davea571** [comment]
Yes, that fixed the problem.  Thank you!
