### ISSUE TITLE
Performance > PropertyAccess

### ISSUE THREAD

**Issue by Detzler** [orocommerce/orocommerce#38]
Hi,

orocommerce has nice performance out of the box. On my local dev machine, I have loading times on the frontend about 500ms with php7.1, but why not make it faster :)

I just did a xdebug dump and played it through webgrind to visualize the execution times.
As you see, the symfony component "propertyAccess" is one of the big time consumers.

![bildschirmfoto vom 2017-06-17 10-36-28](https://user-images.githubusercontent.com/1556434/27251691-3cf55a90-534c-11e7-96fb-35ac9b5aea81.png)

![bildschirmfoto vom 2017-06-17 10-54-07](https://user-images.githubusercontent.com/1556434/27251694-48e9104e-534c-11e7-80b7-5b67a617ee6e.png)

Is it possible to implement a caching strategy or something?
What are your current plans regarding performance in general?

**Comment by aivus** [comment]
Hi, @Detzler.

`PropertyAccess` component [already has cache out-of box](https://github.com/symfony/property-access/blob/43f19429ef128373f30549456e5b363255d4789d/PropertyAccessor.php#L109-L117).

In new services OroCommerce uses `@property_accessor` service to inject same service and reuse cache.

Unfortunately, old services are creating their own instance of PropertyAccessor with `PropertyAccess::createPropertyAccessor()`.

We have appropriate ticket to use this service everywhere, but I can't provide any ETA.

Internal ticket: BAP-9316

**Comment by Detzler** [comment]
thanks a lot
