### ISSUE TITLE
why no composer.json defined for each bundle? 

### ISSUE THREAD

**Issue by videni** [orocommerce/orocommerce#41]

**Comment by aivus** [comment]
Hi, @videni 

Bundles/components which distribute separately have their own `composer.json` files.
It doesn't make sense to have `composer.json` files in each bundle, because they are could not be used separately.

**Comment by manowark** [comment]
Hi, @videni. Do you have additional questions related to this issue?

**Comment by videni** [comment]
@manowark, thanks for asking, I have  no more question,  let me close this.
