### ISSUE TITLE
FallbackBundle use?

### ISSUE THREAD

**Issue by StephenOTT** [orocommerce/orocommerce#6]
Can you explain what the FallbackBundle is used for in relation to translation?

**Comment by mbessolov** [comment]
FallbackBundle provides form types to build a UI that editing data that can have different values in different scopes (e.g. a value that can be translated into different languages, or should be different on the different websites, etc.).

You may check the product edit page (product name, product descriptions) or category edit page to see how it looks and works (click on the icon next to the input field / textarea to see additional inputs).
