### ISSUE TITLE
Wrong PHP version required

### ISSUE THREAD

**Issue by Djamy** [orocommerce/orocommerce#8]
Hello !

Just to notify that we can not install vendors with php version under 5.5.

This is the result of a composer install with PHP 5.4.45:
`Problem 1
    - Installation request for doctrine/cache v1.6.0 -> satisfiable by doctrine/cache[v1.6.0].
    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.`
  `Problem 2
    - Installation request for zendframework/zend-code 2.6.3 -> satisfiable by zendframework/zend-code[2.6.3].
    - zendframework/zend-code 2.6.3 requires php ^5.5 || 7.0.0 - 7.0.4 || ^7.0.6 -> your PHP version (5.4.45) does not satisfy that requirement.`
  `Problem 3
    - Installation request for zendframework/zend-eventmanager 3.0.1 -> satisfiable by zendframework/zend-eventmanager[3.0.1].
    - zendframework/zend-eventmanager 3.0.1 requires php ^5.5 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.`
  `Problem 4
    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - doctrine/doctrine-cache-bundle 1.3.0 requires doctrine/cache ^1.4.2 -> satisfiable by doctrine/cache[v1.6.0].
    - Installation request for doctrine/doctrine-cache-bundle 1.3.0 -> satisfiable by doctrine/doctrine-cache-bundle[1.3.0].`

So we have a conflict with requirements specified in the [orocommerce-application's Readme](https://github.com/orocommerce/orocommerce-application/blob/master/README.md)

**Comment by mbessolov** [comment]
Hello @Djamy ,

Thank you for reporting the issue. The upcoming OroPlatform version 1.10 will no work on PHP 5.4.x.
We will update the supported version numbers in the  README file.

Thank you.

**Comment by Djamy** [comment]
Fixed in one of your latest commit, thanks. I close this myself :)
